name: flutter_app
description: 🧮 Calculadora simples usando estado nativo do Flutter (atividade da disciplina de Prog. para Dispositivos Móveis II na FATEC de São José dos Campos)

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true